### ISSUE TITLE
CTRLDeck crashes when main window is closed

### ISSUE THREAD

**Issue by y0mo1337** [Narfjones/CTRLDeck#2]
On Windows 11, if the CTRL deck is connected via COM port and audio is playing, the program will crash instead of closing to the tray when the main window is exited. Observed on Brett's black-and-white, 16-button, 4-switch CTRLDeck hardware.

**Comment by ngc6027** [comment]
This has been happening on my Windows 10 machine as well. Doesn't seem to happen as frequently (or at all?) if I haven't connected to the hardware.

**Comment by Narfjones** [comment]
Seems to have been resolved with the previous issue.
